### ISSUE TITLE
Is there table style?

### ISSUE THREAD

**Issue by khoshroomahdi** [OfficeDev/office-ui-fabric-core#1186] opened 2019-08-11 16:29 UTC

**Comment by Jahnp** [comment] 2019-08-19 23:00
Hi @khoshroomahdi , there is not a table style or Table component, but Fabric React does include a [DetailsList component](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist), which is similar:
![image](https://user-images.githubusercontent.com/307118/63305090-5cd92e80-c29a-11e9-8a32-58a1dd6504cf.png)

I would recommend evaluating that component to see if it better suits your needs. I'm going to close this out as Fabric Core does not include component styles by design. Thank you!

**Closed by Jahnp** 2019-08-19 23:00 UTC
