### ISSUE TITLE
Compile issues with Typescript 2.4.1

### ISSUE THREAD

**Issue by LarsLiden** [OfficeDev/office-ui-fabric-core#1000] opened 2017-07-11 15:45 UTC
I'm seeing a number of compile errors with Typescript 2.4.1.

Here's a couple examples:
ERROR in [at-loader] ./node_modules/@uifabric/utilities/lib/Customizer.d.ts:40:55 
    TS2559: Type 'ICustomizerProps' has no properties in common with type 'IBaseProps'.

ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/components/Calendar/CalendarDay.d.ts:30:56 
    TS2559: Type 'ICalendarDayProps' has no properties in common with type 'IBaseProps'.

**Comment by Jahnp** [comment] 2017-07-11 15:51
Hi @LarsLiden, it looks like this issue is a duplicate of https://github.com/OfficeDev/office-ui-fabric-react/issues/2128, and doesn't apply to Fabric Core; I'll close this for now.

**Closed by Jahnp** 2017-07-11 15:51 UTC
